"""
config.py
----------
Loads environment variables from .env (via python-dotenv) and exposes
typed config constants used across the system.
"""
import os
from pathlib import Path

# Load .env file if present (falls back to real env vars silently)
try:
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=Path(__file__).parent / ".env")
except ImportError:
    pass  # python-dotenv not installed; rely on shell env vars

# --- Google Gemini API -------------------------------------------------------
GOOGLE_API_KEY: str = os.environ.get("GOOGLE_API_KEY", "")
GEMINI_MODEL: str = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")
USE_AI_NARRATIVE: bool = bool(GOOGLE_API_KEY and GOOGLE_API_KEY != "your_google_api_key_here")

# --- Analysis configuration --------------------------------------------------
PRICE_HISTORY_PERIOD: str = os.environ.get("PRICE_HISTORY_PERIOD", "1y")
MOVING_AVERAGE_WINDOWS: list[int] = [20, 50, 200]
RSI_WINDOW: int = 14
RISK_FREE_RATE: float = float(os.environ.get("RISK_FREE_RATE", "0.065"))

# --- Output configuration ----------------------------------------------------
OUTPUT_DIR: str = os.environ.get("OUTPUT_DIR", "output")
DEFAULT_FORMAT: str = os.environ.get("DEFAULT_FORMAT", "markdown")
SUPPORTED_FORMATS: list[str] = ["markdown", "html", "pdf"]

# --- Compliance / disclaimer -------------------------------------------------
DISCLAIMER = (
    "This report is generated by an automated AI-assisted system for "
    "personal research and demonstration purposes. It does not constitute "
    "investment advice, a recommendation, or an offer to buy or sell any "
    "security. All figures are derived from third-party market data sources "
    "and may contain inaccuracies or delays. Always independently verify "
    "data points and consult applicable regulatory guidelines before acting "
    "on any information contained herein."
)

REPORT_PREPARED_BY = "AI-Powered Stock Report Generation System"
